// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj_RPnoumKA6BPnWlqyGqYlTRZzsnA-TE',
    appId: '1:791049472656:web:d87ded4c6fa879504b6615',
    messagingSenderId: '791049472656',
    projectId: 'agroflow-52f2e',
    authDomain: 'agroflow-52f2e.firebaseapp.com',
    storageBucket: 'agroflow-52f2e.firebasestorage.app',
    measurementId: 'G-0BLHSGT9E0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAker1vOZr3ER8NB-VhvIzLSuJ62xX4ojA',
    appId: '1:791049472656:ios:87082f0899b59aac4b6615',
    messagingSenderId: '791049472656',
    projectId: 'agroflow-52f2e',
    storageBucket: 'agroflow-52f2e.firebasestorage.app',
    iosBundleId: 'com.agroflow.agroflow',
    databaseURL: 'https://agroflow-52f2e-default-rtdb.firebaseio.com', // Added
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAker1vOZr3ER8NB-VhvIzLSuJ62xX4ojA',
    appId: '1:791049472656:ios:87082f0899b59aac4b6615',
    messagingSenderId: '791049472656',
    projectId: 'agroflow-52f2e',
    storageBucket: 'agroflow-52f2e.firebasestorage.app',
    iosBundleId: 'com.agroflow.agroflow',
    databaseURL: 'https://agroflow-52f2e-default-rtdb.firebaseio.com', // Added
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWFYdkqBGDiwkh2L_qQMMUGqCo4fngn2E',
    appId: '1:791049472656:android:440cce45975f2a7d4b6615',
    messagingSenderId: '791049472656',
    projectId: 'agroflow-52f2e',
    storageBucket: 'agroflow-52f2e.firebasestorage.app',
    databaseURL: 'https://agroflow-52f2e-default-rtdb.firebaseio.com', // Added
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj_RPnoumKA6BPnWlqyGqYlTRZzsnA-TE',
    appId: '1:791049472656:web:df18b7892f9cca714b6615',
    messagingSenderId: '791049472656',
    projectId: 'agroflow-52f2e',
    authDomain: 'agroflow-52f2e.firebaseapp.com',
    storageBucket: 'agroflow-52f2e.firebasestorage.app',
    measurementId: 'G-L0VVHG1PLC',
  );

}